# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x] # Dropping this to 14. Don't see any point in earlier builds.

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }} # Establishes environment
    # https://github.com/oxr463/setup-cordova
    #- run: npm ci
    #- run: npm run build --if-present
    #- run: npm test
    - name: Use oxr463/setup-cordova
      uses: oxr463/setup-cordova@0.0.2
      with:
        exec: |
          cordova platform add android && \
          cordova build --no-telemetry && \
          cp "$(find . -name '*.apk')" .
